<?
$PERM["personal-cabinet-salesman"]["8"]="W";
$PERM["personal-cabinet-salesman"]["7"]="R";
$PERM["personal-cabinet-salesman"]["*"]="D";
$PERM["personal-cabinet-buyer"]["8"]="W";
$PERM["personal-cabinet-buyer"]["6"]="R";
$PERM["personal-cabinet-buyer"]["*"]="D";
$PERM["/"]["*"]="R";
$PERM["/"]["G8"]="W";
$PERM["services"]["G5"]="W";
$PERM["services"]["G8"]="W";
$PERM["ads"]["G8"]="W";
$PERM["main"]["G8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>